/** @file Server.cpp
 *  This file contains methods and tasks needed to setup and run a web server hotspot
 *  from an ESP32 microcontroller. A lot of this code is taken from John Ridgely's 
 *  in-class example which sets up a WiFi hotspot on an ESP32; the rest of it, including
 *  most of the HTML handling and live plotting, is generated by ChatGPT 5.1.
*/

#include <Arduino.h>
#include "Shares.h"
#include "Driver.h"
#include "PrintStream.h"
#include "taskshare.h"
#include "taskqueue.h"
#include "WebServer.h"

/** Extern declarations for the objects created in main.cpp */
extern Driver Peripheral;

// Credentials and network parameters for ESP32
const char* ssid = "RW2";   // SSID, network name seen on LAN lists
const char* password = "telemetry";   // ESP32 WiFi password (min. 8 characters)

/* Put IP Address details */
IPAddress local_ip (192, 168, 5, 1); // Address of ESP32 on its own network
IPAddress gateway (192, 168, 5, 1);  // The ESP32 acts as its own gateway
IPAddress subnet (255, 255, 255, 0); // Network mask; just leave this as is

// Create the server object
WebServer server (80);

/** @brief   Get the WiFi running
 * 
 *  @details This function sets up the WiFi access point on the ESP32. It is called in setup() in main.cpp.
 */
void setup_wifi (void)
{
    Serial << "Setting up WiFi access point...";
    WiFi.mode (WIFI_AP);
    WiFi.softAPConfig (local_ip, gateway, subnet);
    WiFi.softAP (ssid, password);
    Serial << "done." << endl;
}

/** @brief   Put a web page header into an HTML string. 
 *  @param   a_string A reference to a string to which the header is added; the
 *           string must have been created in each function that calls this one
 *  @param   page_title The title of the page
*/
void HTML_header (String& a_string, const char* page_title)
{
    a_string += "<!DOCTYPE html> <html>\n";
    a_string += "<head><meta name=\"viewport\" content=\"width=device-width,";
    a_string += " initial-scale=1.0, user-scalable=no\">\n<title> ";
    a_string += page_title;
    a_string += "</title>\n";
    a_string += "<style>html { font-family: Helvetica; display: inline-block;";
    a_string += " margin: 0px auto; text-align: center;}\n";
    a_string += "body{margin-top: 50px;} h1 {color: #4444AA;margin: 50px auto 30px;}\n";
    a_string += "p {font-size: 24px;color: #222222;margin-bottom: 10px;}\n";
    a_string += "</style>\n</head>\n";
}

/** @brief   Callback function that responds to HTTP requests without a subpage
 *  name.
 * 
 *  @details This creates a page which includes forms to command speed and torque, along with
 *  live gain tuning. It includes a live readout of the commanded speed and actual speed of the 
 *  motor.
 */
void handle_DocumentRoot ()
{
    Serial << "HTTP request from client #" << server.client () << endl;

    // --- Handle incoming GET parameters on the server side ---

    // Torque command (in N·m, goes to outer loop)
    if (server.hasArg("torque"))
    {
        String torque_str = server.arg("torque");
        float torque_web = torque_str.toFloat();

        // Outer-loop command: torque -> Controller -> speed_cmd
        torque_cmd.put(torque_web);
    }

    // Direct speed command (RPM, bypass torque loop)
    if (server.hasArg("speed_cmd"))
    {
        String speed_cmd_str = server.arg("speed_cmd");
        float speed_cmd_rpm = speed_cmd_str.toFloat();

        // Inner-loop command: direct speed command in RPM
        speed_cmd.put(speed_cmd_rpm);
        last_speed_cmd.put(speed_cmd_rpm);
    }

    // Write kp to controller queue
    if (server.hasArg("kp"))
    {
        String kp_str = server.arg("kp");
        float kp_val = kp_str.toFloat();
        kp.put(kp_val);
    }

    // Write kd to controller queue
    if (server.hasArg("kd"))
    {
        String kd_str = server.arg("kd");
        float kd_val = kd_str.toFloat();
        kd.put(kd_val);
    }
       
    // Write SPEED to the DRV8308
    if (server.hasArg("SPEED"))
    {
        String speed_str = server.arg("SPEED");
        uint16_t speed_val = speed_str.toInt();
        Peripheral.drv_write(0x0B, speed_val);
        Serial.println("Set SPEED to " + String(speed_val));
        Serial.println("DRV8308 register 0x0B expected: 0x12C, actual:" + String(Peripheral.drv_read(0x0B)));
    }

    // Write ADVANCE (bits 7:0) to the DRV8308 register 0x01
    if (server.hasArg("ADVANCE"))
    {
        String advance_str = server.arg("ADVANCE");
        uint16_t advance_val = advance_str.toInt();

        uint16_t reg01 = Peripheral.drv_read(0x01);
        uint16_t new_reg01 = (reg01 & 0xFF00) | (advance_val & 0x00FF);
        Peripheral.drv_write(0x01, new_reg01);
    }

    // --- Build HTML page ---
    String a_str;
    a_str.reserve(30000);
    HTML_header(a_str, "Motor Control");

    // ============== The following layout was built by ChatGPT 5.1 ==============

    // Simple layout + typography to fit on one screen
    a_str += "<style>\n";
    a_str += "  body { margin: 8px; font-family: Arial, sans-serif; font-size: 13px; }\n";
    a_str += "  #layout { display: flex; flex-direction: row; align-items: flex-start; gap: 12px; }\n";
    a_str += "  #leftPanel { flex: 0 0 280px; max-width: 320px; }\n";
    a_str += "  #rightPanel { flex: 1 1 auto; }\n";
    a_str += "  h1 { font-size: 18px; margin: 4px 0 8px 0; }\n";
    a_str += "  h2 { font-size: 14px; margin: 8px 0 4px 0; }\n";
    a_str += "  h3 { font-size: 13px; margin: 4px 0; }\n";
    a_str += "  form { margin: 4px 0 6px 0; padding: 4px; border: 1px solid #ddd; border-radius: 4px; }\n";
    a_str += "  form p { margin: 2px 0 4px 0; font-size: 12px; }\n";
    a_str += "  input[type=\"number\"] { width: 100%; box-sizing: border-box; font-size: 12px; }\n";
    a_str += "  input[type=\"submit\"] { margin-top: 4px; font-size: 12px; padding: 2px 6px; }\n";
    a_str += "  p.status { margin: 0 0 2px 0; font-size: 11px; min-height: 1em; }\n";
    a_str += "</style>\n";

    a_str += "<body>\n";
    a_str += "<div id=\"layout\">\n";

    // ===== LEFT PANEL: forms =====
    a_str += "<div id=\"leftPanel\">\n";

    a_str += "<h1>Motor Control Interface</h1>\n";

    // ----- Torque command form -----
    a_str += "<h2>Torque Command</h2>\n";
    a_str += "<form id=\"torqueForm\" action=\"/\" method=\"GET\">\n";
    a_str += "  <p>Enter torque command (N·m):</p>\n";
    a_str += "  <input type=\"number\" step=\"0.001\" name=\"torque\" required>\n";
    a_str += "  <input type=\"submit\" value=\"Send\">\n";
    a_str += "</form>\n";
    a_str += "<p id=\"status_torque\" class=\"status\"></p>\n";

    // ----- Speed command form -----
    a_str += "<h2>Speed Command</h2>\n";
    a_str += "<form id=\"speedCmdForm\" action=\"/\" method=\"GET\">\n";
    a_str += "  <p>Enter speed command (RPM):</p>\n";
    a_str += "  <input type=\"number\" step=\"1\" name=\"speed_cmd\" required>\n";
    a_str += "  <input type=\"submit\" value=\"Send\">\n";
    a_str += "</form>\n";
    a_str += "<p id=\"status_speed_cmd\" class=\"status\"></p>\n";

    // ----- Gain forms -----
    a_str += "<h2>Gain Settings</h2>\n";

    // kp
    a_str += "<p id=\"status_kp\" class=\"status\"></p>\n";
    a_str += "<form id=\"kpForm\" action=\"/\" method=\"GET\">\n";
    a_str += "  <p>kp:</p>\n";
    a_str += "  <input type=\"number\" step=\"0.001\" name=\"kp\" required>\n";
    a_str += "  <input type=\"submit\" value=\"Set kp\">\n";
    a_str += "</form>\n";

    // kd
    a_str += "<p id=\"status_kd\" class=\"status\"></p>\n";
    a_str += "<form id=\"kdForm\" action=\"/\" method=\"GET\">\n";
    a_str += "  <p>kd:</p>\n";
    a_str += "  <input type=\"number\" step=\"0.001\" name=\"kd\" required>\n";
    a_str += "  <input type=\"submit\" value=\"Set kd\">\n";
    a_str += "</form>\n";

    // SPEED reference
    a_str += "<p id=\"status_SPEED\" class=\"status\"></p>\n";
    a_str += "<form id=\"SPEEDForm\" action=\"/\" method=\"GET\">\n";
    a_str += "  <p>SPEED reference (0 to 4095):</p>\n";
    a_str += "  <input type=\"number\" step=\"1\" min=\"0\" max=\"4095\" name=\"SPEED\" required>\n";
    a_str += "  <input type=\"submit\" value=\"Set SPEED Ref\">\n";
    a_str += "</form>\n";

    // ADVANCE (bits 7:0 of 0x01)
    a_str += "<p id=\"status_ADVANCE\" class=\"status\"></p>\n";
    a_str += "<form id=\"ADVANCEForm\" action=\"/\" method=\"GET\">\n";
    a_str += "  <p>ADVANCE (bits 7:0) (0 to 255):</p>\n";
    a_str += "  <input type=\"number\" step=\"1\" min=\"0\" max=\"255\" name=\"ADVANCE\" required>\n";
    a_str += "  <input type=\"submit\" value=\"Set ADVANCE\">\n";
    a_str += "</form>\n";


    a_str += "</div>\n"; // end leftPanel

    // ===== RIGHT PANEL: plot =====
    a_str += "<div id=\"rightPanel\">\n";
    a_str += "<h2>Actual Speed vs Time</h2>\n";
    a_str += "<h3>Live RPM Plot</h3>\n";
    a_str += "<canvas id=\"speedCanvas\" width=\"600\" height=\"350\" ";
    a_str += "style=\"border:1px solid #000000;\"></canvas>\n";
    a_str += "<br/>\n";
    a_str += "<button id=\"downloadBtn\" type=\"button\" onclick=\"downloadCSV()\">Download CSV</button>\n";
    a_str += "</div>\n"; // end rightPanel
    a_str += "</div>\n"; // end layout

    // ----- JavaScript: forms + plot -----
    a_str += "<script>\n";

    // Data arrays
    a_str += "let data = [];\n";        // actual RPM
    a_str += "let timeData = [];\n";    // time stamps
    a_str += "let cmdData = [];\n";     // commanded RPM history

    // for limited display
    // a_str += "let maxPoints = 100;\n";

    a_str += "let startTime = Date.now();\n";
    a_str += "const canvas = document.getElementById('speedCanvas');\n";
    a_str += "const ctx = canvas.getContext('2d');\n";

    a_str += "function drawPlot(){\n";
    a_str += "  ctx.clearRect(0,0,canvas.width,canvas.height);\n";
    a_str += "  if(data.length < 2) return;\n";

    a_str += "  let tmin = timeData[0];\n";
    a_str += "  let tmax = timeData[timeData.length-1];\n";
    a_str += "  let ymin = Math.min(...data);\n";
    a_str += "  let ymax = Math.max(...data);\n";

    a_str += "  for(let i=0;i<cmdData.length;i++){\n";
    a_str += "    if(!isNaN(cmdData[i])){\n";
    a_str += "      ymin = Math.min(ymin, cmdData[i]);\n";
    a_str += "      ymax = Math.max(ymax, cmdData[i]);\n";
    a_str += "    }\n";
    a_str += "  }\n";

    a_str += "  if(ymax === ymin){ ymin -= 1; ymax += 1; }\n";

    a_str += "  let left=60, right=20, top=20, bottom=50;\n";

    a_str += "  ctx.strokeStyle='#000';\n";
    a_str += "  ctx.beginPath();\n";
    a_str += "  ctx.moveTo(left, top);\n";
    a_str += "  ctx.lineTo(left, canvas.height-bottom);\n";
    a_str += "  ctx.lineTo(canvas.width-right, canvas.height-bottom);\n";
    a_str += "  ctx.stroke();\n";

    a_str += "  ctx.font='12px Arial';\n";
    a_str += "  ctx.textAlign='right';\n";
    a_str += "  ctx.textBaseline='middle';\n";

    a_str += "  for(let i=0;i<=5;i++){\n";
    a_str += "    let val = ymin + i*(ymax-ymin)/5;\n";
    a_str += "    let y = canvas.height-bottom - (val-ymin)/(ymax-ymin)*(canvas.height-top-bottom);\n";
    a_str += "    ctx.fillText(val.toFixed(0), left-8, y);\n";
    a_str += "  }\n";

    a_str += "  ctx.textAlign='center';\n";
    a_str += "  ctx.textBaseline='top';\n";

    a_str += "  for(let i=0;i<=5;i++){\n";
    a_str += "    let tval = tmin + i*(tmax-tmin)/5;\n";
    a_str += "    let x = left + (tval-tmin)/(tmax-tmin)*(canvas.width-left-right);\n";
    a_str += "    ctx.fillText(tval.toFixed(1), x, canvas.height-bottom+8);\n";
    a_str += "  }\n";

    a_str += "  ctx.strokeStyle='#000';\n";
    a_str += "  ctx.beginPath();\n";
    a_str += "  for(let i=0;i<data.length;i++){\n";
    a_str += "    let x = left + (timeData[i]-tmin)/(tmax-tmin)*(canvas.width-left-right);\n";
    a_str += "    let y = canvas.height-bottom - (data[i]-ymin)/(ymax-ymin)*(canvas.height-top-bottom);\n";
    a_str += "    if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y);\n";
    a_str += "  }\n";
    a_str += "  ctx.stroke();\n";

    a_str += "  ctx.strokeStyle='#ff0000';\n";
    a_str += "  ctx.beginPath();\n";
    a_str += "  let first=true;\n";
    a_str += "  for(let i=0;i<cmdData.length;i++){\n";
    a_str += "    if(isNaN(cmdData[i])) continue;\n";
    a_str += "    let x = left + (timeData[i]-tmin)/(tmax-tmin)*(canvas.width-left-right);\n";
    a_str += "    let y = canvas.height-bottom - (cmdData[i]-ymin)/(ymax-ymin)*(canvas.height-top-bottom);\n";
    a_str += "    if(first){ ctx.moveTo(x,y); first=false; }\n";
    a_str += "    else ctx.lineTo(x,y);\n";
    a_str += "  }\n";
    a_str += "  if(!first) ctx.stroke();\n";

    a_str += "}\n";


    // Helper: attach AJAX behavior so forms don't refresh the page
    a_str += "function attachAjaxForm(formId, paramName, statusId, label, updateCmd){\n";
    a_str += "  const form = document.getElementById(formId);\n";
    a_str += "  if (!form) return;\n";
    a_str += "  form.addEventListener('submit', function(e){\n";
    a_str += "    e.preventDefault();\n";
    a_str += "    const formData = new FormData(form);\n";
    a_str += "    const val = formData.get(paramName);\n";
    a_str += "    if (val === null || val === '') return;\n";
    a_str += "    const url = '/?' + encodeURIComponent(paramName) + '=' + encodeURIComponent(val);\n";
    a_str += "    fetch(url)\n";
    a_str += "      .then(r => r.text())\n";
    a_str += "      .then(function(txt){\n";
    a_str += "        const st = document.getElementById(statusId);\n";
    a_str += "        if (st) st.innerHTML = '<b>' + label + val + '</b>';\n";
    a_str += "      })\n";
    a_str += "      .catch(function(err){ console.log(err); });\n";
    a_str += "  });\n";
    a_str += "}\n";

    // Attach handlers for all forms (no page reload)
    a_str += "attachAjaxForm('torqueForm',    'torque',    'status_torque',    'Last torque command sent: ', false);\n";
    a_str += "attachAjaxForm('speedCmdForm',  'speed_cmd', 'status_speed_cmd', 'Last speed command sent: ', true);\n";
    a_str += "attachAjaxForm('kpForm',        'kp',        'status_kp',        'Last kp value: ', false);\n";
    a_str += "attachAjaxForm('kdForm',        'kd',        'status_kd',        'Last kd value: ', false);\n";
    a_str += "attachAjaxForm('SPEEDForm',     'SPEED',     'status_SPEED',     'Last SPEED reference value: ', false);\n";
    a_str += "attachAjaxForm('ADVANCEForm',   'ADVANCE',   'status_ADVANCE',   'Last ADVANCE value: ', false);\n";

    // Download CSV function
    a_str += "function downloadCSV(){\n";
    a_str += "  if(data.length === 0){\n";
    a_str += "    alert('No data to download yet');\n";
    a_str += "    return;\n";
    a_str += "  }\n";
    a_str += "  let csv = 'Time (s),Actual Speed (RPM),Commanded Speed (RPM)\\n';\n";
    a_str += "  for(let i=0;i<data.length;i++){\n";
    a_str += "    csv += timeData[i].toFixed(3) + ',' + data[i].toFixed(2) + ',';\n";
    a_str += "    if(!isNaN(cmdData[i])){\n";
    a_str += "      csv += cmdData[i].toFixed(2);\n";
    a_str += "    }\n";
    a_str += "    csv += '\\n';\n";
    a_str += "  }\n";
    a_str += "  const blob = new Blob([csv], {type: 'text/csv'});\n";
    a_str += "  const url = window.URL.createObjectURL(blob);\n";
    a_str += "  const a = document.createElement('a');\n";
    a_str += "  a.href = url;\n";
    a_str += "  a.download = 'motor_data_' + new Date().getTime() + '.csv';\n";
    a_str += "  document.body.appendChild(a);\n";
    a_str += "  a.click();\n";
    a_str += "  document.body.removeChild(a);\n";
    a_str += "  window.URL.revokeObjectURL(url);\n";
    a_str += "}\n";


    // Fetch latest RPM from /speed
    a_str += "function fetchSpeed(){\n";
    a_str += "  Promise.all([\n";
    a_str += "    fetch('/speed').then(r => r.text()),\n";
    a_str += "    fetch('/speed_cmd_actual').then(r => r.text())\n";
    a_str += "  ]).then(values => {\n";
    a_str += "    let rpm = parseFloat(values[0]);\n";
    a_str += "    let cmd = parseFloat(values[1]);\n";
    a_str += "    let t = (Date.now() - startTime)/1000.0;\n";
    a_str += "    if(!isNaN(rpm)){\n";
    a_str += "      data.push(rpm);\n";
    a_str += "      timeData.push(t);\n";
    a_str += "      cmdData.push(isNaN(cmd) ? NaN : cmd);\n";
    a_str += "      drawPlot();\n";
    a_str += "    }\n";
    a_str += "  }).catch(e => { console.log(e); });\n";
    a_str += "}\n";

    a_str += "fetchSpeed();\n";
    a_str += "setInterval(fetchSpeed, 200);\n";

    a_str += "</script>\n";

    server.send(200, "text/html", a_str);
}

/** @brief   Respond to a request for an HTTP page that doesn't exist.
 *  @details This function produces the Error 404, Page Not Found error. 
 */
void handle_NotFound (void)
{
    server.send (404, "text/plain", "Not found");
}

/** @brief   HTTP handler which reports the current measured motor speed.
 *  @details When a client accesses the @c /speed endpoint, this function reads
 *  the latest RPM value from the shared variable @c speed_actual and
 *  returns it as plain text. This endpoint is intended for JavaScript
 *  polling to generate real-time plots in the browser UI.
 */
void handle_Speed (void)
{
    // Read the latest measured speed (RPM)
    bool direction = Peripheral.get_dir(); // read direction pin
    float rpm = speed_actual.get();  // Share<float> from Shares.h

    String out;
    out += String(rpm, 2); // 2 decimal places
    server.send(200, "text/plain", out);
}

/** @brief   HTTP handler which reports the latest commanded speed.
 *  @details When a client accesses the /speed_cmd_actual endpoint,
 *           this function reads the most recent commanded RPM from
 *           the speed_cmd queue (or share) and returns it as plain text.
 */
void handle_SpeedCmd (void)
{
    float cmd_rpm = last_speed_cmd.get();  // same pattern as speed_actual.get()

    String out;
    out += String(cmd_rpm, 2);
    server.send(200, "text/plain", out);
}

/** @brief   Task which sets up and runs a web server.
 *  @details After setup, function @c handleClient() must be run periodically
 *           to check for page requests from web clients. One could run this
 *           task as the lowest priority task with a short or no delay, as there
 *           generally isn't much rush in replying to web queries.
 */
void task_webserver (void* p_params)
{
    // The server has been created statically when the program was started and
    // is accessed as a global object because not only this function but also
    // the page handling functions referenced below need access to the server
    server.on ("/", handle_DocumentRoot);
    server.on ("/speed", handle_Speed);
    server.on("/speed_cmd_actual", handle_SpeedCmd);
    server.onNotFound (handle_NotFound);

    // Get the web server running
    server.begin ();
    Serial.println ("HTTP server started");

    for (;;)
    {
        // The web server must be periodically run to watch for page requests
        server.handleClient ();
        vTaskDelay (10); 
    }
}
